name: ruby-openai

type: ruby

up:
  - ruby: 3.2.2
  - bundler

commands:
  console:
    desc: 'start a console'
    run: bin/console
  run:
    desc: 'start the application'
    run: bin/run
  test:
    syntax:
      argument: file
      optional: args...
    run: bin/testunit
